project_name: simple-server-status
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - binary: sssd
    main: ./dashboard/app.go
    id: sssd
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X simple-server-status/dashboard/common.Version={{.Version}}
      - -X simple-server-status/dashboard/common.BuiltAt={{.Date}}
      - -X simple-server-status/dashboard/common.GitCommit={{.FullCommit}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
  - binary: sssa
    main: ./agent/agent.go
    id: sssa
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X simple-server-status/agent/common.Version={{.Version}}
      - -X simple-server-status/agent/common.BuiltAt={{.Date}}
      - -X simple-server-status/agent/common.GitCommit={{.FullCommit}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - id: sssd
    builds:
      - sssd
    format: tar.gz
    wrap_in_directory: true
    name_template: 'sssd-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE*
      - README*.md
      - sss-dashboard.yaml.example
  - id: sssa
    builds:
      - sssa
    format: tar.gz
    wrap_in_directory: true
    name_template: 'sssa-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*.md
      - sss-agent.yaml.example
      - sssa.service
dockers:
  - id: sssd
    dockerfile: ./Dockerfile
    use: buildx
    image_templates:
      - "ruanun/sssd:{{ .Version }}"
      - "ruanun/sssd:latest"
      - "ruanun/sssd"

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

