project_name: simple-server-status
version: 2
builds:
  - id: sssa
    binary: sssa
    main: ./main.go
    hooks:
      pre:
        - go mod tidy
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X simple-server-status/agent/global.Version={{.Version}}
      - -X simple-server-status/agent/global.BuiltAt={{.Date}}
      - -X simple-server-status/agent/global.GitCommit={{.FullCommit}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - id: sssa
    builds:
      - sssa
    format: tar.gz
    wrap_in_directory: true
    name_template: 'sssa-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - sssa.service
      - sss-agent.yaml.example
checksum:
  name_template: 'sssa-{{ .Version }}-checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

